[package]
name = "liba"
version = "0.1.9"
authors = ["tqfx <tqfx@tqfx.org>"]
edition = "2018"
description = "An algorithm library based on C/C++"
documentation = "https://tqfx.org/liba/"
repository = "https://github.com/tqfx/liba.git"
homepage = "https://github.com/tqfx/liba.git"
license = "MPL-2.0"
keywords = ["algorithm"]
categories = ["algorithms"]

[build-dependencies]
cmake = "0.1"

[features]
std = []
# floating-point number are stored using C’s float type
float = []
