name: freebsd
on:
  workflow_dispatch:
jobs:
  FreeBSD:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { type: Debug },
          { type: Release },
        ]
    runs-on: ubuntu-latest
    env:
      LIBA_OPENMP: 1
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - uses: vmactions/freebsd-vm@v1
        with:
          envs: 'LIBA_OPENMP CTEST_OUTPUT_ON_FAILURE'
          copyback: false
          prepare: |
            pkg install -y curl gmake cmake rust python openjdk8
            curl -sSL https://bootstrap.pypa.io/get-pip.py | python -
          run: |
            python -m venv venv
            . venv/bin/activate
            python -m pip install -r requirements.txt
            cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.type }} \
              -DBUILD_TESTING=1 \
              -DLIBA_WARNINGS=1 \
              -DLIBA_ANALYZER=1 \
              -DLIBA_SANITIZE=1 \
              -DLIBA_WITH_LUA=1 \
              -DLIBA_PYTHON=1 \
              -DLIBA_VCPKG=1 \
              -DLIBA_JAVA=1 \
              -DLIBA_LIBTOOL=1 \
              -DLIBA_PKGCONFIG=1
            cmake --build build --config ${{ matrix.type }} --target package
            cmake --build build --target test
            cargo test
