name: mingw
on:
  workflow_dispatch:
jobs:
  MinGW:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { mingw: MinGW64 },
          { mingw: MinGW32 },
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: Run setup
        run: |
          set -x
          sudo apt-get -y install nsis mingw-w64
      - name: Run cmake
        run: |
          set -x
          cmake -S . -B build --toolchain cmake/Use${{ matrix.mingw }}.cmake \
            -DBUILD_TESTING=1 \
            -DLIBA_WARNINGS=1 \
            -DLIBA_ANALYZER=1 \
            -DLIBA_STATIC=1
          cmake --build build --target package
