name: xmake
on:
  workflow_dispatch:
jobs:
  unix:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          actions-cache-key: xmake
          actions-cache-folder: _
      - name: Run cargo
        run: cargo test --all-features
      - name: Run setup
        run: |
          python3 -m venv _
          . _/bin/activate
          python3 -m pip install -r requirements.txt
          env
      - name: Run xmake f
        run: |
          . _/bin/activate
          xmake f -yvDc -m check --warning=y --liba-rust=y --liba-java=y --liba-lua=lua --liba-python=python --liba-quickjs=y
      - name: Run xmake b
        run: |
          . _/bin/activate
          xmake b --all -v
      - name: Run xmake i
        run: |
          . _/bin/activate
          xmake i -vD -o_
      - name: Run xmake r
        run: |
          . _/bin/activate
          xmake r --all
  msvc:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          actions-cache-key: xmake
          actions-cache-folder: _
      - name: Run cargo
        run: cargo test --all-features
      - name: Run setup
        run: |
          python -m venv _
          _/Scripts/Activate.ps1
          python -m pip install -r requirements.txt
          Get-ChildItem Env: | Sort Name
      - name: Run xmake f
        run: |
          _/Scripts/Activate.ps1
          xmake f -yvDc -m check --warning=y --liba-rust=y --liba-java=y --liba-lua=lua --liba-python=python --liba-quickjs=y
      - name: Run xmake b
        run: |
          _/Scripts/Activate.ps1
          xmake b --all -v
      - name: Run xmake i
        run: |
          _/Scripts/Activate.ps1
          xmake i -vD -o_
      - name: Run xmake r
        run: |
          _/Scripts/Activate.ps1
          xmake r --all
